In [1]:
import pandas as pd

In [2]:
lh_path = "C:\\Users\\ytsma22c\\Google Drive\\Misc Work\\LOD paper\\ChemLIBS_LOD_calcs_byhand.csv"
lod_hand = pd.read_csv(lh_path)
la_path = "C:\\Users\\ytsma22c\\Google Drive\\Misc Work\\LOD paper\\LOD_calcs.csv"
lod_auto = pd.read_csv(la_path)
th_path = "C:\\Users\\ytsma22c\\Google Drive\\Misc Work\\LOD paper\\ChemLIBS_test_calcs_byhand.csv"
test_hand = pd.read_csv(th_path)
ta_path = "C:\\Users\\ytsma22c\\Google Drive\\Misc Work\\LOD paper\\test_calcs.csv"
test_auto = pd.read_csv(ta_path)

In [4]:
lod_hand.columns == lod_auto.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [7]:
lod = lod_hand.append(lod_auto).reset_index(drop=True)
lod

,element,instrument,atmosphere,num_range,vector,LOB_Braga,LOB_metals,LOD_Braga,LOD_metals,LOQ_Braga,LOQ_metals
0,SiO2,ChemLIBS,Mars,0-750,9027.525145,4.200157,1.752289,8.400313,3.504578,25.455495,10.619934
1,MnO,ChemLIBS,Mars,0-750,260.473316,0.121188,0.050559,0.242376,0.101118,0.734473,0.306419
2,Na2O,ChemLIBS,Mars,0-750,826.045923,0.384327,0.160340,0.768654,0.320680,2.329255,0.971756
3,Li,ChemLIBS,Mars,0-750,8164.698980,3.798717,1.584810,7.597434,3.169620,23.022529,9.604910
4,Ni,ChemLIBS,Mars,0-750,15529.825720,7.225425,3.014419,14.450849,6.028838,43.790452,18.269207
...,...,...,...,...,...,...,...,...,...,...,...
67,Pb,LANL,Mars,250-1000,389.004579,0.157228,0.058845,0.315411,0.118048,0.955792,0.357720
68,Rb,LANL,Mars,250-1000,3630.195718,1.467252,0.549142,2.943423,1.101622,8.919463,3.338250
69,SiO2,LANL,Mars,250-1000,5296.175940,2.140607,0.801156,4.294227,1.607182,13.012809,4.870249
70,Sr,LANL,Mars,250-1000,143705.565467,58.082881,21.738435,116.518850,43.609019,353.087423,132.148543
71,Zn,LANL,Mars,250-1000,5094.189508,2.058968,0.770601,4.130453,1.545887,12.516525,4.684507

In [5]:
test_hand.columns == test_auto.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
test = test_hand.append(test_auto).reset_index(drop=True)
test

,element,instrument,atmosphere,num_range,Avg_Braga,Avg_metals,RMSEP_Braga,RMSEP_metals,R2_Braga,R2_metals
0,SiO2,ChemLIBS,Mars,0-750,3.470097,58.550747,5.420919,5.418319,0.842805,0.844139
1,MnO,ChemLIBS,Mars,0-750,4.044496,0.885416,2.217964,0.949485,0.701163,0.879940
2,Na2O,ChemLIBS,Mars,0-750,58.597755,2.940708,0.780032,0.776745,0.610594,0.683162
3,Li,ChemLIBS,Mars,0-750,40.620303,27.831588,25.376510,19.819523,0.248116,0.430351
4,Ni,ChemLIBS,Mars,0-750,124.003487,103.062296,102.035372,92.370528,0.426234,0.486326
...,...,...,...,...,...,...,...,...,...,...
67,Pb,LANL,Mars,250-1000,16.261339,16.174956,11.940771,11.901814,0.208756,0.210586
68,Rb,LANL,Mars,250-1000,92.097213,90.128480,39.030775,38.584039,0.687352,0.697074
69,SiO2,LANL,Mars,250-1000,57.342051,57.342051,2.855192,2.855192,0.949434,0.949434
70,Sr,LANL,Mars,250-1000,466.166667,284.777647,52.437566,42.487355,0.793037,0.909333
71,Zn,LANL,Mars,250-1000,91.327122,90.511955,52.281691,51.997454,0.353613,0.362004

## Export
Replace the existing `LOD_calcs` and `test_calcs` files

In [9]:
le_path = "C:\\Users\\ytsma22c\\Google Drive\\Misc Work\\LOD paper\\LOD_calcs.csv"
te_path = "C:\\Users\\ytsma22c\\Google Drive\\Misc Work\\LOD paper\\test_calcs.csv"
lod.to_csv(le_path, index=False)
test.to_csv(te_path, index=False)