In [8]:
import pandas as pd

In [9]:
lh_path = "C:\\Users\\ytsma22c\\Google Drive\\Darby Work\\LOD paper\\ChemLIBS_LOD_calcs_byhand.csv"
lod_hand = pd.read_csv(lh_path)
la_path = "C:\\Users\\ytsma22c\\Google Drive\\Darby Work\\LOD paper\\LOD_calcs.csv"
lod_auto = pd.read_csv(la_path)
th_path = "C:\\Users\\ytsma22c\\Google Drive\\Darby Work\\LOD paper\\ChemLIBS_test_calcs_byhand.csv"
test_hand = pd.read_csv(th_path)
ta_path = "C:\\Users\\ytsma22c\\Google Drive\\Darby Work\\LOD paper\\test_calcs.csv"
test_auto = pd.read_csv(ta_path)

In [10]:
lod_hand.columns == lod_auto.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [11]:
lod = lod_hand.append(lod_auto).reset_index(drop=True)
lod

,element,instrument,atmosphere,num_range,vector,LOB_Braga,LOB_metals,LOD_Braga,LOD_metals,LOQ_Braga,LOQ_metals
0,SiO2,ChemLIBS,Mars,0-750,9027.525145,4.200157,1.752289,8.400313,3.504578,25.455495,10.619934
1,MnO,ChemLIBS,Mars,0-750,260.473316,0.121188,0.050559,0.242376,0.101118,0.734473,0.306419
2,Na2O,ChemLIBS,Mars,0-750,826.045923,0.384327,0.160340,0.768654,0.320680,2.329255,0.971756
3,Li,ChemLIBS,Mars,0-750,8164.698980,3.798717,1.584810,7.597434,3.169620,23.022529,9.604910
4,Ni,ChemLIBS,Mars,0-750,15529.825720,7.225425,3.014419,14.450849,6.028838,43.790452,18.269207
...,...,...,...,...,...,...,...,...,...,...,...
121,Pb,LANL,Mars,250-1000,520.481655,0.210368,0.078734,0.422015,0.157946,1.278834,0.478624
122,Rb,LANL,Mars,250-1000,7499.395355,3.031104,1.134438,6.080634,2.275773,18.426163,6.896282
123,SiO2,LANL,Mars,250-1000,8542.342845,3.452642,1.292206,6.926273,2.592267,20.988706,7.855354
124,Sr,LANL,Mars,250-1000,111411.378542,45.030224,16.853272,90.334189,33.808996,273.739966,102.451504
125,Zn,LANL,Mars,250-1000,14459.090656,5.844072,2.187236,11.723670,4.387769,35.526272,13.296268

In [12]:
test_hand.columns == test_auto.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
test = test_hand.append(test_auto).reset_index(drop=True)
test

,element,instrument,atmosphere,num_range,Avg_Braga,Avg_metals,RMSEP_Braga,RMSEP_metals,R2_Braga,R2_metals
0,SiO2,ChemLIBS,Mars,0-750,58.597755,58.550747,5.420919,5.418319,0.842805,0.844139
1,MnO,ChemLIBS,Mars,0-750,4.044496,0.885416,2.217964,0.949485,0.701163,0.879940
2,Na2O,ChemLIBS,Mars,0-750,3.470097,2.940708,0.780032,0.776745,0.610594,0.683162
3,Li,ChemLIBS,Mars,0-750,40.620303,27.831588,25.376510,19.819523,0.248116,0.430351
4,Ni,ChemLIBS,Mars,0-750,124.003487,103.062296,102.035372,92.370528,0.426234,0.486326
...,...,...,...,...,...,...,...,...,...,...
121,Pb,LANL,Mars,250-1000,16.786241,16.527991,16.495796,16.368837,0.178842,0.189404
122,Rb,LANL,Mars,250-1000,97.385494,90.021522,27.756921,26.687355,0.811857,0.838157
123,SiO2,LANL,Mars,250-1000,57.112753,55.644556,4.033074,4.063333,0.890554,0.922536
124,Sr,LANL,Mars,250-1000,444.363967,257.265019,133.327433,95.447464,0.255817,0.706744
125,Zn,LANL,Mars,250-1000,74.670337,64.703057,40.612659,38.105105,0.262361,0.383381

## Export
Replace the existing `LOD_calcs` and `test_calcs` files

In [14]:
le_path = "C:\\Users\\ytsma22c\\Google Drive\\Darby Work\\LOD paper\\LOD_calcs.csv"
te_path = "C:\\Users\\ytsma22c\\Google Drive\\Darby Work\\LOD paper\\test_calcs.csv"
lod.to_csv(le_path, index=False)
test.to_csv(te_path, index=False)